FROM postgres:9.3-alpine

ADD target/persistence-0.0.1.jar persistence.jar

ENV POSTGRES_DB scraper
ENV POSTGRES_USER scraper
ENV POSTGRES_PASSWORD password

RUN apk add --no-cache bash
RUN apk add openjdk8

# CMD ["java", "-jar", "/persistence.jar"]
