# Start with a base image containing Java runtime
FROM openjdk:8-jdk-alpine

# The application's jar file
ARG JAR_FILE=target/ArticleProcessor-0.1.0.jar

# Add the application's jar to the container
ADD ${JAR_FILE} ArticleProcessor.jar

# Run the jar file 
ENTRYPOINT ["java","-Xmx400m", "-Xms400m","-jar","/ArticleProcessor.jar"]